spring.application.name=internship-java-2026-korolchuk

spring.datasource.url=jdbc:postgresql://localhost:5432/BusinessTrips

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update